export const hookCategoryOverrides: Record<string, string> = {
  useTextareaAutoSize: 'Elements',
  useClickOutside: 'Elements',
  useDraggable: 'Elements',
  useElementSize: 'Elements',
  useElementBounding: 'Elements',
  useElementVisibility: 'Elements',
  useParentElement: 'Elements',
  useWindowFocus: 'Elements',
  useWindowScroll: 'Elements',
  useActiveElement: 'Elements',
  useDropZone: 'Elements',

  useHash: 'Browser',
  useBrowserLocation: 'Browser',
  useBroadcastChannel: 'Browser',
  useFavicon: 'Browser',
  useFileDialog: 'Browser',
  useFileSystemAccess: 'Browser',
  useFullscreen: 'Browser',
  useMediaQuery: 'Browser',
  useMediaControls: 'Browser',
  useMemory: 'Browser',
  useCssSupports: 'Browser',
  useCssVar: 'Browser',
  useBreakpoints: 'Browser',
  useBluetooth: 'Browser',
  usePreferredColorScheme: 'Browser',
  usePreferredDark: 'Browser',
  useDark: 'Browser',
  usePreferredLanguages: 'Browser',
  usePreferredReducedMotion: 'Browser',
  usePreferredContrast: 'Browser',
  usePreferredReducedTransparency: 'Browser',
  useTextDirection: 'Browser',
  useColorMode: 'Browser',
  useUrlSearchParams: 'Browser',
  useSSRWidth: 'Browser',
  useScreenOrientation: 'Browser',
  useShare: 'Browser',
  useVibrate: 'Browser',
  useWakeLock: 'Browser',
  useStyleTag: 'Browser',
  useWebNotification: 'Browser',
  useScreenSafeArea: 'Browser',
  useWindowSize: 'Browser',
  useTitle: 'Browser',
  useLockBodyScroll: 'Browser',
  useScript: 'Browser',
  usePageVisibility: 'Browser',
  useCopyToClipboard: 'Browser',
  usePermission: 'Browser',
  usePerformanceObserver: 'Browser',

  useIdle: 'Sensors',
  useImage: 'Browser',
  useIntersectionObserver: 'Sensors',
  useResizeObserver: 'Sensors',
  useMutationObserver: 'Sensors',
  useOnline: 'Sensors',
  useNavigatorLanguage: 'Sensors',
  useNetwork: 'Sensors',
  useMouse: 'Sensors',
  useScroll: 'Sensors',
  usePageLeave: 'Sensors',
  useFocus: 'Sensors',
  useFocusWithin: 'Sensors',
  useMousePressed: 'Sensors',
  useElementHover: 'Sensors',
  useElementByPoint: 'Sensors',
  useTextSelection: 'Sensors',
  useDevicePixelRatio: 'Sensors',
  useDisplayMedia: 'Sensors',
  useDeviceMotion: 'Sensors',
  useDeviceOrientation: 'Sensors',
  useDevicesList: 'Sensors',
  useFps: 'Sensors',
  useGeolocation: 'Sensors',
  useGamepad: 'Browser',
  useKeyModifier: 'Sensors',
  usePointer: 'Sensors',
  useParallax: 'Sensors',
  useInfiniteScroll: 'Sensors',
  useMagicKeys: 'Sensors',
  useSwipe: 'Sensors',
  useSpeechRecognition: 'Sensors',
  useSpeechSynthesis: 'Sensors',
  useUserMedia: 'Sensors',

  useAsync: 'Network',
  useAbortController: 'Network',
  useFetch: 'Network',
  useWebSocket: 'Network',
  useWebWorker: 'Browser',
  useWebWorkerFn: 'Browser',
  useEventSource: 'Network',

  useRafState: 'Animation',
  useIntervalFn: 'Animation',
  useTimeoutFn: 'Animation',
  useRafFn: 'Animation',
  useAnimate: 'Animation',
  usePresenceTransition: 'Animation',

  useOnMount: 'Component',
  useMountedState: 'Component',
  useVirtualList: 'Component',

  useEventListener: 'Watch',
  watchImmediate: 'Watch',
  watchOnce: 'Watch',
  whenever: 'Watch',
  watchDebounced: 'Watch',
  watchThrottled: 'Watch',
  watchAtMost: 'Watch',
  watchArray: 'Watch',
  watchPausable: 'Watch',
  watchTriggerable: 'Watch',
  watchWithFilter: 'Watch',
  watchDeep: 'Watch',
  watchIgnorable: 'Watch',
  useEventCallback: 'Reactivity',
  refAutoReset: 'Reactivity',
  refDebounced: 'Reactivity',
  refThrottled: 'Reactivity',

  useSorted: 'Array',
  useCycleList: 'Array',
  useStepper: 'Array',
  useArrayMap: 'Array',
  useArrayFilter: 'Array',
  useArrayReduce: 'Array',
  useArrayFind: 'Array',
  useArrayFindIndex: 'Array',
  useArraySome: 'Array',
  useArrayIncludes: 'Array',
  useArrayJoin: 'Array',
  useArrayEvery: 'Array',
  useArrayDifference: 'Array',
  useArrayFindLast: 'Array',
  useArrayUnique: 'Array',

  useTimeout: 'Time',
  useInterval: 'Time',
  useNow: 'Time',
  useTimestamp: 'Time',
  useDateFormat: 'Time',
  useTimeAgo: 'Time',
  useTimeAgoIntl: 'Time',
  useCountdown: 'Time',

  useLocalStorage: 'Utilities',
  useSessionStorage: 'Utilities',
  useCloned: 'Utilities',
  useDebounceFn: 'Utilities',
  useThrottleFn: 'Utilities',
  useMemoize: 'Utilities',
  useEventBus: 'Utilities',
  useToNumber: 'Utilities',
  useToString: 'Utilities',
  useSupported: 'Utilities',
  useCached: 'Utilities',
  useTimeoutPoll: 'Utilities',
  createEventHook: 'Utilities',
  createGlobalState: 'Utilities',
  createInjectionState: 'Utilities',
  createSharedComposable: 'Utilities',
  isDefined: 'Utilities',
  get: 'Utilities',
  set: 'Utilities',
  createUnrefFn: 'Utilities',
  makeDestructurable: 'Utilities',
  onKeyStroke: 'Sensors',
  onElementRemoval: 'Sensors',
  onLongPress: 'Sensors',
  onStartTyping: 'Sensors',
  useBase64: 'Utilities',
  useBattery: 'Sensors',
  useAsyncQueue: 'Utilities',
  useOffsetPagination: 'Utilities',
  useObjectUrl: 'Browser',
  useConfirmDialog: 'Utilities',

  useToggle: 'State',
  useCounter: 'State',
  useDebounce: 'State',
  usePrevious: 'State',
  useLatest: 'State',
  useThrottle: 'State',
  useAsyncState: 'State',
  useStorage: 'State',
  useStorageAsync: 'State',
  useLastChanged: 'State',
  useRefHistory: 'State',
  useManualRefHistory: 'State',
  useDebouncedRefHistory: 'State',
  useThrottledRefHistory: 'State',
}

export const categoryToSlug: Record<string, string> = {
  State: 'state',
  Elements: 'elements',
  Browser: 'browser',
  Sensors: 'sensors',
  Network: 'network',
  Animation: 'animation',
  Component: 'component',
  Watch: 'watch',
  Reactivity: 'reactivity',
  Array: 'array',
  Time: 'time',
  Utilities: 'utilities',
}

export const slugToCategory: Record<string, string> = Object.fromEntries(
  Object.entries(categoryToSlug).map(([category, slug]) => [slug, category]),
)

const categoryAliases: Record<string, string> = {
  Storage: 'Utilities',
  Async: 'Network',
  Lifecycle: 'Component',
  Performance: 'Animation',
}

export function normalizeHookCategory(hookName: string | undefined, category?: string) {
  if (hookName && hookCategoryOverrides[hookName]) return hookCategoryOverrides[hookName]
  if (!category) return 'Utilities'
  return categoryAliases[category] || category
}

export function getCategoryFromPath(pathname: string) {
  const match = pathname.match(/^\/functions\/([^/]+)\/?$/)
  if (!match) return null
  return slugToCategory[match[1].toLowerCase()] || null
}

export function getCategoryPath(category: string) {
  const slug = categoryToSlug[category]
  if (!slug) return '/functions/'
  return `/functions/${slug}`
}
